name: freelancediteur
description: Editeur de recueils de faits surnaturels vecus, BD, recueils d’histoires drôles vécues.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # BASE
  intl: ^0.18.1

  # COMMON
  nb_utils: ^6.0.7

  firebase_core: ^2.24.0
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9

  # STATE MANAGEMENT
  mobx: ^2.1.1
  flutter_mobx: ^2.0.6+4

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.0.4

  # AUTHENTICATION
  google_sign_in: ^6.1.6
  the_apple_sign_in: 1.1.1

  # CONNECTIVITY
  http: ^0.13.5

  # ADS
  google_mobile_ads: ^4.0.0

  # VIDEOS
  video_player: ^2.4.7
  chewie: any

  # AUDIO
  just_audio: ^0.9.30

  # PDF File
  flutter_pdfview: ^1.2.5

  # EPUB File
  epub_view: ^3.0.0

  # WEB TOOLS
  webview_flutter: ^4.4.2
  html_unescape: 2.0.0

  # IMAGES
  cached_network_image: ^3.2.2
  image_picker: ^1.0.4

  # SPLASH SCREEN
  splash_screen_view: ^2.0.1

  # UI
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.9
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  dots_indicator: ^3.0.0
  auto_size_text: ^3.0.0
  otp_text_field: ^1.1.3
  country_code_picker: ^3.0.0
  lottie: ^2.7.0
  flutter_vector_icons: ^2.0.0
  flutter_html: ^3.0.0-alpha.2
  aes_crypt_null_safe: ^2.0.2

  # STORAGE
  permission_handler: ^11.1.0

  # LAUNCH URL
  url_launcher: ^6.1.6

  # DOWNLOAD
  internet_file: ^1.2.0

  # DATABASE
  sqflite: ^2.1.0+1

  # PAYMENTS
  razorpay_flutter: ^1.3.3

  ## The reason for the lack of support for flutter 3.0.0 is the temporary comment paystack payment code
  #flutter_paystack: ^1.0.5+1
  #flutter_inappwebview: ^5.4.3+7

  #ANIMATION
  flutter_staggered_animations: ^1.1.1

  palette_generator: ^0.3.3+2

  #VOICE SEARCH
  speech_to_text: ^6.1.0

  flutter_localizations:
    sdk: flutter

  package_info_plus: ^1.4.2
  audio_session: ^0.1.18
  firebase_analytics: ^10.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.7+3
  build_runner: ^2.3.2

dependency_overrides:
  firebase_core_platform_interface: 5.0.0
  package_info_plus: ^4.0.1
  wakelock_windows: any
  win32: any

flutter:
  uses-material-design: true
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - lang/en.json
    - lang/fr.json
    - lang/es.json
    - lang/af.json
    - lang/de.json
    - lang/in.json
    - lang/vi.json
    - lang/tr.json
    - lang/hi.json
    - lang/ar.json
    - lang/pt.json
    - lang/zh.json

  fonts:
    - family: Jost
      fonts:
        - asset: fonts/Jost-Bold.ttf
        - asset: fonts/Jost-Italic.ttf
        - asset: fonts/Jost-Medium.ttf
        - asset: fonts/Jost-Regular.ttf
