// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4k0yxy0d-VrzllYQlTTEtklpAEhg215Q',
    appId: '1:791669722094:android:400e4133418e6e72e69cff',
    messagingSenderId: '791669722094',
    projectId: 'freelancediteur-6ff38',
    storageBucket: 'freelancediteur-6ff38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuW6E14_mAmNwQN3Gdc5rJw5aHAuKed0M',
    appId: '1:791669722094:ios:86b94b48bd926dfde69cff',
    messagingSenderId: '791669722094',
    projectId: 'freelancediteur-6ff38',
    storageBucket: 'freelancediteur-6ff38.appspot.com',
    androidClientId: '791669722094-c3j6gtgrdfle0dj6nke7jbi2ji79q1f1.apps.googleusercontent.com',
    iosClientId: '791669722094-jsmugdp58c1nl19vqeh1oa324k1ijba1.apps.googleusercontent.com',
    iosBundleId: 'com.dicompro.freelancediteur',
  );
}
